//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercywatch
{
    using System;
    using System.Collections.Generic;
    
    public partial class Heroes
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string WinRate { get; set; }
    
        public virtual Players Players { get; set; }
    }
}
